---
- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
- name: copying files
  ansible.builtin.copy:
    src:  /home/patel/My-Portfolio/website/files/
    dest: /var/www/html
    owner: root
    group: root
    mode: '777'
